### ISSUE TITLE
Don't support youtube play list 

### ISSUE THREAD

**Issue by KiriTowaha** [KingRain/SimpleDiscordMusicBot#1]
![image](https://user-images.githubusercontent.com/64723622/134008562-12823add-8486-485d-a85d-90405b35a4c6.png)
don't support youtube play list(public) ????

**Comment by KiriTowaha** [comment]
[https://www.youtube.com/playlist?list=PLTRkBgepZZEWwZe6EKN_BDVMzctVA_j7S](url) the link

**Comment by hoktophen** [comment]
Fixed with youtube api: `https://developers.google.com/youtube/v3/getting-started`

**Comment by KiriTowaha** [comment]
Fixed with youtube api key [https://developers.google.com/youtube/v3/getting-started](url)
